version: "3.7"
services:
  pause:
    image: k8s.gcr.io/pause:3.1
  web:
    image: 192.168.4.112/lambor/scheduler-frontend:20200918092745
    pid: service:pause
    environment:
      - API_HOST=api
    ports:
      - 8080:80
  api:
    image: 192.168.4.112/lambor/scheduler:20200918092535
    pid: service:pause
